#!/bin/bash
# /etc/init.d/presence

### BEGIN INIT INFO
# Provides:          presence
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: presence
# Description:       Python script pour détecter la présence Domoticz via adresse MAC des téléphones
### END INIT INFO


case "$1" in 
    start)
        echo "Starting presence"
        echo "  python /home/pi/domoticz/scripts/python/presence/presence.py &"
        python /home/pi/domoticz/scripts/python/presence/presence.py &
        ;;
    stop)
        echo "Stopping presence"
        echo '  pkill -f "python /home/pi/domoticz/scripts/python/presence/presence.py"'
        pkill -f "python /home/pi/domoticz/scripts/python/presence/presence.py"
        ;;
	reload|restart)
		$0 stop
		sleep 1
		$0 start
		;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0